# Generated by Django 4.2.1 on 2023-05-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_category_comment_post_delete_author_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
